THM-ATLAS/vue-frontend

- src/components/FooterCard.vue
- src/helpers/theme.ts
Fixed colors and `<script setup>` syntax
> Fixed footer design

- src/components/SettingsCard.vue
- src/i18n/de.ts
- src/i18n/en.ts
- src/views/SettingsView.vue
- Changed layout
- Added and extended i18n support
- Utilize `<script setup>`
> 33 improve settings layout and use script setup

- src/components/FooterCard.vue
- src/components/HomeContent.vue
- src/components/LoginModal.vue
- src/components/SearchBar.vue
- src/components/navbar/NavbarBase.vue
- src/router/index.ts
- src/views/HomeView.vue
- landing page is now available with "/"
- moved login page to "/login"
- search bar leads to course page "/courses"
> 9 add a simple landing page

- src/components/HomeContent.vue
- src/components/LoginModal.vue
- src/components/MainPage.vue
- src/components/navigation/navbar/CourseButton.vue
- src/components/navigation/navbar/DropdownCard.vue
- src/components/navigation/navbar/NavbarBase.vue
- src/components/navigation/navbar/SearchBar.vue
- src/i18n/de.ts
- src/i18n/en.ts
The only content of the "main page" (page of a specific course with exercises), which I did translate, was the card's title ("Aufgabe" -> "Exercise"). However, I was not able to do this in the "MainpageCardModal" component and I needed to manipulate the JSON, because of the current design choices and Vue syntax. This solution works for now, but needs a rework. I suggest postponing this rework until the exercises are provided by the backend.
> 76 i18n for main page course page landing page

- src/App.vue
- src/components/exercises/ExerciseCard.vue
- src/i18n/de.ts
- src/i18n/en.ts
- src/main.ts
- src/router/index.ts
- src/services/API.ts
To test, visit /bkm/e/1 (or any currently non-existing task). Other response codes are also supported but not currently received by the API.
> API Error handling using snackbar popup

- src/components/MainPage.vue
- src/components/MainpageCardModal.vue
Changed the green color when in dark mode, other colors look good. This issue might be revisited if the stakeholder is not happy with the current style.
> 81 improve dark theme colors esp green

- src/components/CourseMainPage.vue
- src/components/CourseMainPageContainer.vue
- src/components/CourseSearch.vue
- src/components/CourseSearchResult.vue
- src/components/MainPage.vue
- src/components/MainpageCardModal.vue
- src/components/exercises/ExerciseCard.vue
- src/components/exercises/ExerciseEditor.vue
- src/components/helpers/SkipToContent.vue
- src/services/ModuleService.ts
Integrated redesigned CoursePages with API responses, kind of made CourseMainPageContainer obsolete in the process.
> Individual course pages from api

- src/components/helpers/SkipToContent.vue
Link now appears centered on top of header.
> Fixed Link Positioning

- src/components/navigation/navbar/NavbarBase.vue
The admin page can now be accessed in mobile view.
> Added button to mobile navigation

- src/components/LoginModal.vue
This was the only leftover use of "green" in the project.
> Using new highlight-color

- src/components/admin/ModuleManagement.vue
- src/components/admin/NavbarAdmin.vue
- src/helpers/types.ts
- src/i18n/de.ts
- src/i18n/en.ts
- src/router/index.ts
- src/services/ModuleService.ts
- src/views/admin/ModuleManagementView.vue
- src/views/admin/TaskManagementView.vue
- src/views/admin/UserManagementView.vue
Created module panel, should be working as expected
> 77 admin module management panel

- src/components/CourseMainPage.vue
Looking like the one in the execise editor on mobile and desktop view.
Closes #119
> Added back button to individual course pages

- src/components/helpers/SkipToContent.vue
- src/helpers/theme.ts
added color variable for skipLink
> Fixed coloring

- src/components/CourseMainPage.vue
- src/i18n/de.ts
- src/i18n/en.ts
> redesigned module page

- src/components/CourseMainPage.vue
- src/components/CourseSearchResult.vue
- src/components/HomeContent.vue
- src/components/navigation/PageNotFound.vue
- src/components/navigation/navbar/NavbarBase.vue
- src/i18n/de.ts
- src/i18n/en.ts
Made some adjustments based on errors and warnings generated by the WAVE add-on.
> 108 test UI for accessibility issues

- src/components/SettingsCard.vue
- src/i18n/localeHelper.ts
- src/main.ts
- src/views/SettingsView.vue
Closes #152 and #144 and #166 and #167
> Implemented language setting persistence

- src/components/CourseMainPage.vue
- src/components/CourseMainPageContainer.vue
- src/components/CourseSearch.vue
- src/components/CourseSearchResult.vue
- src/i18n/de.ts
- src/i18n/en.ts
Implemented Pagination, needs styling though 
Also refactored course to module here and there
Closes #156
> 156 pagination on course overview does not work

- src/components/admin/NavbarAdmin.vue
To test:
visit http://localhost:8080/admin/ as mobile view (navbar is open at first)
visit http://localhost:8080/admin/users as mobile view (navbar is closed at first)
> close mobile navbar panelper default except for on /admin/

- docker-compose.dev.yaml
- docker-compose.yaml
- src/components/LoginModal.vue
- src/components/ProfileCard.vue
- src/components/navigation/navbar/DropdownCard.vue
- src/components/navigation/navbar/NavbarBase.vue
- src/helpers/types.ts
- src/services/API.ts
- src/services/LoginService.ts
- src/services/UserService.ts
- vue.config.js
Login via /login is now possible when the backend runs locally.    
Upon visiting /home you'll get prompted to log in via a simple form that you can cancel away - this will be fixed later.     
Logout leads to an error. This is a backend issue. You'll still be logged out.     
Also closes #175.
> 202 major store token received from login page and send it with api

- docker-compose.dev.yaml
Closes #217 
Just had to move environment variable from compose file to env file
> 217 bug docker compose file for backend does not work

- src/services/API.ts
- src/services/LoginService.ts
Works with newest backend version
> Fixed api base link

- src/components/admin/UserManagement.vue
The global role tutor now can't be assigned anymore.
I also removed the role from everyone
> Removed tutor from checkbox-list

- src/components/ModuleManager.vue
- src/components/exercises/ExerciseEditor.vue
> Fix buttons displaying above table header

- src/components/exercises/ExerciseCard.vue
> ExerciseCard now changes router URL when the exercise can't be found

- src/components/SettingsCard.vue
> the selected theme now is the disabled button

- vue.config.js
frontend development now works on firefox
> added proxy setting for backend run on localhost:8080

- .github/workflows/codeql.yml
- README.md
- src/router/index.ts
Backup of the docker block for sometime in the future
1. Klonen des Frontend Repos   
1. Über HTTPS  
`git clone https://github.com/THM-ATLAS/vue-frontend.git`  
2. Über ssh  
`git clone git@github.com:THM-ATLAS/vue-frontend.git`   
2. Anlegen des Environment Files für den Datenbankzugriff  
Die Platzhalter müssen natürlich mit den richtigen Credentials der Datenbank ersetzt werden!
```
cd <Frontend Repo> && echo "db_source=<Link zur Datenbank>\ndb_username=<Datenbank Username>\ndb_password=<Datenbank Passwort>\nmode=api-dev" > backend_db_credentials.env
```  
3. Starten der App und des lokalen Backends für die Entwicklung  
Dabei wird immer das neueste Image des Backends verwendet.   
` docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml pull && docker-compose -f …
> Update README and CodeQL Workflow

- src/components/module/ModuleMainPage.vue
- src/helpers/permissions.ts
> Module manager button can now only be seen by admin and teacher of the current course

- src/components/admin/ModuleManagement.vue
- src/components/exercises/ExerciseEditor.vue
- src/components/module/ModuleMainPage.vue
- src/components/module/ModuleSearch.vue
- src/i18n/de.ts
- src/i18n/en.ts
> General fixes and improvements

- src/components/admin/ModuleManagement.vue
> 430 bug can not create a module

- src/components/exercises/ExerciseCard.vue
- src/components/exercises/ExerciseCreator.vue
- src/components/exercises/ExerciseEditor.vue
- src/components/module/ModuleMainPage.vue
- src/components/module/ModuleSearch.vue
Fix #402, Fix #409, Close #428
Fix #410 but no ellipsis
> Various fixes
